version: "3"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "$PORT:$PORT"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis_db

  redis_db:
    image: redis
    expose:
      - 6379